name: sync and commit data from d4armory.io

on:
  schedule:
    # this minute, 12, carefully selected with google `random number 10-59` to *try* and
    # reduce load bursts on the world.  *try*...
    - cron: '12 */12 * * *' # every 12 hours
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          ref: main
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: pip
      - run: pip install -r requirements.txt
      - run: python main.py
        env: 
          ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'auto-commit of character sync from d4armory.io'
          
